### ISSUE TITLE
Add GH action for updating GitHub metadata

### ISSUE THREAD

**Issue by hafen** [hafen/htmlwidgetsgallery#88]
@yutannihilation I noticed that you added such an action to the ggplot2 extensions gallery which looks to be modeled after this gallery (which is great!). Do you have any pointers for getting such an action plugged in here?

**Comment by yutannihilation** [comment]
> which looks to be modeled after this gallery

Oh, I didn't know this fact! Thanks for your work.

I think it's easier for me to create a pull request than to explain the details (because I forgot everything). Let me check.

**Comment by hafen** [comment]
Awesome thanks! It's something I've been wanting to do for a while but haven't had time to get into it so I was glad to see that you did it already.
